### ISSUE TITLE
App Sometimes Unresponsive After Pressing Ctrl

### ISSUE THREAD

**Issue by Michael8021** [egoist/whispo#5]
Description:
I am experiencing an issue where the app becomes unresponsive after pressing the Ctrl key. This problem typically occurs after using the app for an extended period, and it requires a restart to restore functionality.

Steps to Reproduce:
1. Open the app.
2. Use the app normally for a while.
3. Press the Ctrl key.
4. Observe that the app becomes unresponsive.

Expected Behavior:
The app should remain responsive after pressing the Ctrl key.

Actual Behavior:
The app stops responding, and I am unable to perform any actions. Restarting the app resolves the issue.

Additional Information:
- This issue occurs intermittently and does not seem to follow a specific pattern.
- I am using macOS 15.1.

Possible Solutions:
I am unsure of the root cause.

**Comment by egoist** [comment]
I haven't encountered this but it's likely related to [ui](https://github.com/SnosMe/uiohook-napi) which we use to detect keypress event, I'll keep this issue open for now.
